import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import SlickBanner from '@/components/slick/slickBanner'
// import Providers from "./../components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fandak Forush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <div className="bg-info-content min-h-screen flex flex-col">
            <Header />
            <SlickBanner />
            {children}
            <footer className="footer footer-center p-4 bg-base-300 text-base-content">
              <p>Fandak Fororush</p>
            </footer>
          </div>
              
      </body>
    </html>
  );
}
